In [1]:
import numpy as np
from sklearn import preprocessing


data=np.array([[3,5],[7,4],[2,4]])
print(data)
#mean Removal : it means mean=0, std=1
# Way: 1
#mean=average
mean_val=data.mean(axis=0)
print(mean_val)

#standard Deviation
std=data.std(axis=0)

final_val=data-mean_val
print(final_val)
#print(final_val.mean(axis=0))
#print(final_val.std(axis=0))

#Way:2
#scale()
final=preprocessing.scale(data)
print(final)
print(final.mean(axis=0))
print(final_val.std(axis=0))

[[3 5]
 [7 4]
 [2 4]]
[4.         4.33333333]
[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[2.1602469  0.47140452]


In [2]:
import pandas as pd

df=pd.read_csv("Table_77.csv")
print(df)
data=df[['Persons','Males','Females']]
print(data)

print(data.mean(axis=0))
print(data.std(axis=0))

mean_removed_data=preprocessing.scale(data)
print(mean_removed_data.mean(axis=0))
print(mean_removed_data.std(axis=0))

FileNotFoundError: [Errno 2] No such file or directory: 'Table_77.csv'

## Scalling

In [ ]:
data=np.array([[3,5],[7,4],[2,4]])

#Define A Scaller Model for scalling the data
scaller_model=preprocessing.MinMaxScaler()

#Apply data to the model: fit
op1=scaller_model.fit(data)

#Let the model transfer the data according to requirnment : transform
op2=op1.transform(data)

#print the result
print(op2)


In [ ]:
data=np.array([[3,5],[7,4],[2,4]])

#Define A Scaller Model for scalling the data
scaller_model=preprocessing.MinMaxScaler(feature_range=(0,1))

#Apply the data to model and let the model transfer the data accordingly
op=scaller_model.fit_transform(data)
print(op)

## Normalization

In [ ]:
data=np.array([[3,5],[7,4],[2,4]])
op=preprocessing.normalize(data,norm='l1')
print(op)

## Binarization

In [ ]:
data=np.array([[3,5],[7,4],[2,4]])
binarized_data=preprocessing.Binarizer(threshold=5)
op=binarized_data.fit_transform(data)
print(data)
print(op)


## Label Encoding

In [3]:
data=['apple','orange','mango','grapes','apple','orange','mango']
labeled_data=preprocessing.LabelEncoder()
op=labeled_data.fit_transform(data)
print(data)
print(op)


#testing the model
test_data=['mango','grapes']
test_op=labeled_data.transform(test_data)
print(test_op)

#inverse Testing
test_data=[2,0]
test_op=labeled_data.inverse_transform(test_data)
print(test_op)




['apple', 'orange', 'mango', 'grapes', 'apple', 'orange', 'mango']
[0 3 2 1 0 3 2]
[2 1]
['mango' 'apple']


## Scalling

In [ ]:
import numpy as np
from sklearn import preprocessing

data=np.array([[3,5],[7,4],[2,4],[8,10]])
print(data)

#Defining a Model
scaller=preprocessing.MinMaxScaler(feature_range=(-1,0))

#Applying the data to model
Model_fit=scaller.fit(data)

#model rearrange the data
op=Model_fit.transform(data)
print(op)

In [ ]:
data=np.array([[3,5],[7,4],[2,4],[8,10]])
print(data)

#Defining a Model
scaller=preprocessing.MinMaxScaler(feature_range=(0,1))

#Applying the data to model & let the model rearrange the data accordingly
op=scaller.fit_transform(data)
print(op)

## Normalization

In [ ]:
data=np.array([[3,5],[7,4],[2,4],[8,10]])
print(data)

#norm : l1,l2,max
normalized_data=preprocessing.normalize(data,norm='l1')
print(normalized_data)

In [ ]:
#binarization
data=np.array([[3,5],[7,4],[2,4],[8,10]])
print(data)

binarized_data=preprocessing.Binarizer(threshold=5)
op=binarized_data.fit_transform(data)
print(op)

## label Encoding

In [ ]:
data=['orange','kiwi','apple','grapes','kiwi','apple','orange']
label_encoder=preprocessing.LabelEncoder()
op=label_encoder.fit_transform(data)
print(data)
print(op)


#Test Model
test_data=['kiwi','apple']
op_test=label_encoder.transform(test_data)
print(op_test)


#Test Model : inverse
test_data=[1,3]
op_test=label_encoder.inverse_transform(test_data)
print(op_test)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("world_literacy_data.csv")
print(df.head())

df['GDP'] = df['GDP'].replace({'\$': '', ',': ''}, regex=True)
df['GDP'] = pd.to_numeric(df['GDP'])

print(df)
plt.bar(df['Country'],df['GDP'])
plt.show()